/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) F_int_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_axpy CASADI_PREFIX(axpy)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_newton CASADI_PREFIX(newton)
#define casadi_newton_mem CASADI_PREFIX(newton_mem)
#define casadi_norm_inf CASADI_PREFIX(norm_inf)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_axpy(casadi_int n, casadi_real alpha, const casadi_real* x, casadi_real* y) {
  casadi_int i;
  if (!x || !y) return;
  for (i=0; i<n; ++i) *y++ += alpha**x++;
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_norm_inf(casadi_int n, const casadi_real* x) {
  casadi_int i;
  casadi_real ret = 0;
  for (i=0; i<n; ++i) ret = casadi_fmax(ret, fabs(*x++));
  return ret;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

struct casadi_newton_mem {
  casadi_int n;
  casadi_real abstol;
  casadi_real abstol_step;
  casadi_real* x;
  casadi_real* g;
  casadi_real* jac_g_x;
  const casadi_int* sp_a;
  const casadi_int* sp_v;
  const casadi_int* sp_r;
  const casadi_int* prinv;
  const casadi_int* pc;
  casadi_real* lin_w;
  casadi_real* lin_v;
  casadi_real* lin_r;
  casadi_real* lin_beta;
};
int casadi_newton(const struct casadi_newton_mem* m) {
    if (m->abstol>0 && casadi_norm_inf(m->n, m->g) <= m->abstol) return 1;
    casadi_qr(m->sp_a, m->jac_g_x, m->lin_w,
              m->sp_v,  m->lin_v, m->sp_r, m->lin_r, m->lin_beta,
              m->prinv, m->pc);
    casadi_qr_solve(m->g, 1, 0, m->sp_v, m->lin_v, m->sp_r, m->lin_r, m->lin_beta,
                    m->prinv, m->pc, m->lin_w);
    casadi_axpy(m->n, -1., m->g, m->x);
    if (m->abstol_step>0 && casadi_norm_inf(m->n, m->g) <= m->abstol_step) return 2;
    return 0;
}

static const casadi_int casadi_s0[70] = {25, 25, 0, 1, 2, 3, 7, 11, 15, 18, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 21, 22, 23, 0, 1, 2, 24, 0, 1, 2, 24, 0, 1, 2, 24, 3, 4, 5, 3, 4, 5, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 20, 19, 15, 0, 1, 2};
static const casadi_int casadi_s1[62] = {25, 25, 0, 1, 2, 3, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 28, 31, 33, 34, 0, 1, 2, 3, 4, 5, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 22, 23, 24, 23, 24, 24};
static const casadi_int casadi_s2[62] = {25, 25, 0, 1, 2, 3, 4, 6, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 30, 34, 0, 1, 2, 3, 3, 4, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 21, 22, 21, 22, 23, 21, 22, 23, 24};
static const casadi_int casadi_s3[25] = {21, 22, 23, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 20, 15, 16, 17, 19, 18, 0, 1, 2, 24};
static const casadi_int casadi_s4[25] = {0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 3, 4, 5, 24};
static const casadi_int casadi_s5[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s6[155] = {151, 1, 0, 151, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150};
static const casadi_int casadi_s7[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s8[5] = {1, 1, 0, 1, 0};

/* g_jac:(i0[25],i1[24],i2[151])->(jac_o0_i0[25x25,42nz],o0[25]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=arg[1]? arg[1][0] : 0;
  a2=5.0000000000000000e-01;
  a3=arg[2]? arg[2][126] : 0;
  a3=(a2*a3);
  a4=500.;
  a5=arg[1]? arg[1][21] : 0;
  a5=(a4*a5);
  a6=(a1/a5);
  a6=(a6+a6);
  a6=(a3*a6);
  a6=(a6/a5);
  a7=(a1*a6);
  a8=arg[2]? arg[2][130] : 0;
  a7=(a7+a8);
  a9=3.1415926535897931e+00;
  a10=5.0000000000000001e-03;
  a11=arg[2]? arg[2][10] : 0;
  a10=(a10*a11);
  a11=2.;
  a12=(a10/a11);
  a12=casadi_sq(a12);
  a9=(a9*a12);
  a12=arg[2]? arg[2][119] : 0;
  a9=(a9*a12);
  a13=(a9*a5);
  a13=(a2*a13);
  a14=3.;
  a13=(a13/a14);
  a14=(a1/a5);
  a15=casadi_sq(a14);
  a16=(a13*a15);
  a7=(a7+a16);
  a16=arg[1]? arg[1][2] : 0;
  a17=(a16/a5);
  a18=(a17*a14);
  a19=(a18+a18);
  a19=(a13*a19);
  a19=(a17*a19);
  a20=arg[1]? arg[1][1] : 0;
  a21=(a20/a5);
  a22=(a21*a14);
  a23=(a22+a22);
  a23=(a13*a23);
  a23=(a21*a23);
  a19=(a19+a23);
  a15=(a15+a15);
  a15=(a13*a15);
  a15=(a13+a15);
  a15=(a14*a15);
  a19=(a19+a15);
  a15=(a14*a19);
  a7=(a7+a15);
  a15=(a11*a13);
  a7=(a7+a15);
  a15=2.7017524800000002e+05;
  a23=1.9634954084936207e-05;
  a23=(a23*a12);
  a23=(a4*a23);
  a23=(a2*a23);
  a23=(a23+a8);
  a12=(a23/a8);
  a12=(a15*a12);
  a24=(a7/a12);
  if (res[0]!=0) res[0][3]=a24;
  a24=(a20*a6);
  a22=(a13*a22);
  a24=(a24+a22);
  a22=(a21*a19);
  a24=(a24+a22);
  a22=(a23/a8);
  a22=(a15*a22);
  a25=(a24/a22);
  if (res[0]!=0) res[0][4]=a25;
  a6=(a16*a6);
  a18=(a13*a18);
  a6=(a6+a18);
  a19=(a17*a19);
  a6=(a6+a19);
  a23=(a23/a8);
  a23=(a15*a23);
  a19=(a6/a23);
  if (res[0]!=0) res[0][5]=a19;
  a19=(a1+a1);
  a19=(a2*a19);
  a18=1000000.;
  a25=500000.;
  a26=arg[2]? arg[2][118] : 0;
  a27=(a11*a26);
  a25=(a25*a27);
  a18=(a18+a25);
  a25=250000.;
  a27=casadi_sq(a26);
  a27=(a25*a27);
  a18=(a18+a27);
  a27=(a19/a18);
  if (res[0]!=0) res[0][6]=a27;
  a27=(a20/a5);
  a27=(a27+a27);
  a27=(a3*a27);
  a27=(a27/a5);
  a28=(a1*a27);
  a29=(a14*a21);
  a30=(a13*a29);
  a28=(a28+a30);
  a30=(a17*a21);
  a31=(a30+a30);
  a31=(a13*a31);
  a31=(a17*a31);
  a32=casadi_sq(a21);
  a33=(a32+a32);
  a33=(a13*a33);
  a33=(a13+a33);
  a33=(a21*a33);
  a31=(a31+a33);
  a29=(a29+a29);
  a29=(a13*a29);
  a29=(a14*a29);
  a31=(a31+a29);
  a29=(a14*a31);
  a28=(a28+a29);
  a29=(a28/a12);
  if (res[0]!=0) res[0][7]=a29;
  a29=(a20*a27);
  a29=(a29+a8);
  a32=(a13*a32);
  a29=(a29+a32);
  a32=(a21*a31);
  a29=(a29+a32);
  a32=(a11*a13);
  a29=(a29+a32);
  a32=(a29/a22);
  if (res[0]!=0) res[0][8]=a32;
  a27=(a16*a27);
  a30=(a13*a30);
  a27=(a27+a30);
  a31=(a17*a31);
  a27=(a27+a31);
  a31=(a27/a23);
  if (res[0]!=0) res[0][9]=a31;
  a31=(a20+a20);
  a31=(a2*a31);
  a30=(a31/a18);
  if (res[0]!=0) res[0][10]=a30;
  a30=(a16/a5);
  a30=(a30+a30);
  a30=(a3*a30);
  a30=(a30/a5);
  a32=(a1*a30);
  a33=(a14*a17);
  a34=(a13*a33);
  a32=(a32+a34);
  a34=casadi_sq(a17);
  a35=(a34+a34);
  a35=(a13*a35);
  a35=(a13+a35);
  a35=(a17*a35);
  a36=(a21*a17);
  a37=(a36+a36);
  a37=(a13*a37);
  a37=(a21*a37);
  a35=(a35+a37);
  a33=(a33+a33);
  a33=(a13*a33);
  a33=(a14*a33);
  a35=(a35+a33);
  a33=(a14*a35);
  a32=(a32+a33);
  a33=(a32/a12);
  if (res[0]!=0) res[0][11]=a33;
  a33=(a20*a30);
  a36=(a13*a36);
  a33=(a33+a36);
  a36=(a21*a35);
  a33=(a33+a36);
  a36=(a33/a22);
  if (res[0]!=0) res[0][12]=a36;
  a30=(a16*a30);
  a30=(a30+a8);
  a34=(a13*a34);
  a30=(a30+a34);
  a35=(a17*a35);
  a30=(a30+a35);
  a35=(a11*a13);
  a30=(a30+a35);
  a35=(a30/a23);
  if (res[0]!=0) res[0][13]=a35;
  a35=(a16+a16);
  a35=(a2*a35);
  a34=(a35/a18);
  if (res[0]!=0) res[0][14]=a34;
  a34=6.9720768776049658e-07;
  a36=arg[2]? arg[2][132] : 0;
  a37=(a34*a36);
  a37=(-a37);
  if (res[0]!=0) res[0][15]=a37;
  a37=arg[2]? arg[2][133] : 0;
  a38=(a34*a37);
  a38=(-a38);
  if (res[0]!=0) res[0][16]=a38;
  a38=arg[2]? arg[2][134] : 0;
  a39=(a34*a38);
  a39=(-a39);
  if (res[0]!=0) res[0][17]=a39;
  a39=arg[2]? arg[2][135] : 0;
  a40=(a34*a39);
  a40=(-a40);
  if (res[0]!=0) res[0][18]=a40;
  a40=arg[2]? arg[2][136] : 0;
  a41=(a34*a40);
  a41=(-a41);
  if (res[0]!=0) res[0][19]=a41;
  a41=arg[2]? arg[2][137] : 0;
  a42=(a34*a41);
  a42=(-a42);
  if (res[0]!=0) res[0][20]=a42;
  a42=arg[2]? arg[2][138] : 0;
  a43=(a34*a42);
  a43=(-a43);
  if (res[0]!=0) res[0][21]=a43;
  a43=arg[2]? arg[2][139] : 0;
  a44=(a34*a43);
  a44=(-a44);
  if (res[0]!=0) res[0][22]=a44;
  a44=arg[2]? arg[2][140] : 0;
  a34=(a34*a44);
  a34=(-a34);
  if (res[0]!=0) res[0][23]=a34;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  a34=9.9501485447727887e+01;
  a45=(a1+a1);
  a46=(a34*a45);
  a46=(a46/a12);
  if (res[0]!=0) res[0][39]=a46;
  a46=(a20+a20);
  a47=(a34*a46);
  a47=(a47/a22);
  if (res[0]!=0) res[0][40]=a47;
  a47=(a16+a16);
  a34=(a34*a47);
  a34=(a34/a23);
  if (res[0]!=0) res[0][41]=a34;
  a34=arg[0]? arg[0][3] : 0;
  a7=(a7*a34);
  a48=arg[0]? arg[0][4] : 0;
  a28=(a28*a48);
  a7=(a7+a28);
  a28=arg[0]? arg[0][5] : 0;
  a32=(a32*a28);
  a7=(a7+a32);
  a32=arg[1]? arg[1][3] : 0;
  a49=(a32*a14);
  a50=arg[1]? arg[1][4] : 0;
  a51=(a50*a21);
  a49=(a49+a51);
  a51=arg[1]? arg[1][5] : 0;
  a52=(a51*a17);
  a49=(a49+a52);
  a52=(a14*a49);
  a53=3.3333333333333331e-01;
  a54=(a4*a9);
  a54=(a2*a54);
  a53=(a53*a54);
  a54=(a52*a53);
  a55=(a14/a5);
  a55=(a4*a55);
  a56=(a49*a55);
  a57=(a32*a55);
  a58=(a21/a5);
  a58=(a4*a58);
  a59=(a50*a58);
  a57=(a57+a59);
  a59=(a17/a5);
  a59=(a4*a59);
  a60=(a51*a59);
  a57=(a57+a60);
  a60=(a14*a57);
  a56=(a56+a60);
  a60=(a13*a56);
  a54=(a54-a60);
  a60=(a32*a1);
  a61=(a50*a20);
  a60=(a60+a61);
  a61=(a51*a16);
  a60=(a60+a61);
  a60=(a60/a5);
  a61=(a60/a5);
  a61=(a4*a61);
  a61=(a61+a61);
  a61=(a3*a61);
  a61=(a61/a5);
  a62=(a60+a60);
  a62=(a62*a3);
  a62=(a62/a5);
  a63=(a62/a5);
  a63=(a4*a63);
  a61=(a61+a63);
  a63=(a1*a61);
  a54=(a54-a63);
  a63=(a51*a53);
  a64=(a17*a49);
  a65=(a64+a64);
  a66=(a65*a53);
  a67=(a49*a59);
  a68=(a17*a57);
  a67=(a67+a68);
  a68=(a67+a67);
  a68=(a13*a68);
  a66=(a66-a68);
  a63=(a63+a66);
  a63=(a17*a63);
  a66=(a51*a13);
  a65=(a65*a13);
  a66=(a66+a65);
  a65=(a66*a59);
  a63=(a63-a65);
  a65=(a50*a53);
  a68=(a21*a49);
  a69=(a68+a68);
  a70=(a69*a53);
  a71=(a49*a58);
  a57=(a21*a57);
  a71=(a71+a57);
  a57=(a71+a71);
  a57=(a13*a57);
  a70=(a70-a57);
  a65=(a65+a70);
  a65=(a21*a65);
  a70=(a50*a13);
  a69=(a69*a13);
  a70=(a70+a69);
  a69=(a70*a58);
  a65=(a65-a69);
  a63=(a63+a65);
  a65=(a32*a53);
  a69=(a52+a52);
  a57=(a69*a53);
  a56=(a56+a56);
  a56=(a13*a56);
  a57=(a57-a56);
  a65=(a65+a57);
  a65=(a14*a65);
  a57=(a32*a13);
  a69=(a69*a13);
  a57=(a57+a69);
  a69=(a57*a55);
  a65=(a65-a69);
  a63=(a63+a65);
  a65=(a14*a63);
  a69=(a17*a66);
  a56=(a21*a70);
  a69=(a69+a56);
  a56=(a14*a57);
  a69=(a69+a56);
  a55=(a69*a55);
  a65=(a65-a55);
  a54=(a54+a65);
  a65=(a32+a32);
  a65=(a65*a53);
  a54=(a54+a65);
  a65=arg[1]? arg[1][22] : 0;
  a54=(a54*a65);
  a7=(a7+a54);
  a54=(a32/a5);
  a54=(a54+a54);
  a54=(a3*a54);
  a54=(a54/a5);
  a55=(a1*a54);
  a55=(a62+a55);
  a56=(a49/a5);
  a72=(a32/a5);
  a73=(a14*a72);
  a56=(a56+a73);
  a73=(a13*a56);
  a55=(a55+a73);
  a73=(a69/a5);
  a74=(a17*a72);
  a75=(a74+a74);
  a75=(a13*a75);
  a75=(a17*a75);
  a72=(a21*a72);
  a76=(a72+a72);
  a76=(a13*a76);
  a76=(a21*a76);
  a75=(a75+a76);
  a57=(a57/a5);
  a56=(a56+a56);
  a56=(a13*a56);
  a56=(a14*a56);
  a57=(a57+a56);
  a75=(a75+a57);
  a57=(a14*a75);
  a73=(a73+a57);
  a55=(a55+a73);
  a55=(a55*a32);
  a73=(a50/a5);
  a73=(a73+a73);
  a73=(a3*a73);
  a73=(a73/a5);
  a57=(a1*a73);
  a56=(a50/a5);
  a76=(a14*a56);
  a77=(a13*a76);
  a57=(a57+a77);
  a77=(a17*a56);
  a78=(a77+a77);
  a78=(a13*a78);
  a78=(a17*a78);
  a70=(a70/a5);
  a79=(a49/a5);
  a56=(a21*a56);
  a79=(a79+a56);
  a56=(a79+a79);
  a56=(a13*a56);
  a56=(a21*a56);
  a70=(a70+a56);
  a78=(a78+a70);
  a76=(a76+a76);
  a76=(a13*a76);
  a76=(a14*a76);
  a78=(a78+a76);
  a76=(a14*a78);
  a57=(a57+a76);
  a57=(a57*a50);
  a55=(a55+a57);
  a57=(a51/a5);
  a57=(a57+a57);
  a57=(a3*a57);
  a57=(a57/a5);
  a76=(a1*a57);
  a70=(a51/a5);
  a56=(a14*a70);
  a80=(a13*a56);
  a76=(a76+a80);
  a66=(a66/a5);
  a80=(a49/a5);
  a81=(a17*a70);
  a80=(a80+a81);
  a81=(a80+a80);
  a81=(a13*a81);
  a81=(a17*a81);
  a66=(a66+a81);
  a70=(a21*a70);
  a81=(a70+a70);
  a81=(a13*a81);
  a81=(a21*a81);
  a66=(a66+a81);
  a56=(a56+a56);
  a56=(a13*a56);
  a56=(a14*a56);
  a66=(a66+a56);
  a56=(a14*a66);
  a76=(a76+a56);
  a76=(a76*a51);
  a55=(a55+a76);
  a7=(a7+a55);
  a60=(a60+a60);
  a60=(a60*a3);
  a60=(a60/a5);
  a3=(a32*a60);
  a55=1.9900297089545577e+02;
  a76=arg[0]? arg[0][24] : 0;
  a55=(a55*a76);
  a55=(a2*a55);
  a45=(a45*a55);
  a3=(a3-a45);
  a45=(a32*a13);
  a52=(a52+a52);
  a52=(a52*a13);
  a45=(a45+a52);
  a52=(a49*a45);
  a76=(a51*a13);
  a56=(a64+a64);
  a56=(a56*a13);
  a76=(a76+a56);
  a56=(a17*a76);
  a81=(a50*a13);
  a82=(a68+a68);
  a82=(a82*a13);
  a81=(a81+a82);
  a82=(a21*a81);
  a56=(a56+a82);
  a14=(a14*a45);
  a56=(a56+a14);
  a14=(a32*a56);
  a52=(a52+a14);
  a52=(a52/a5);
  a3=(a3+a52);
  a7=(a7-a3);
  a3=1.0000000000000001e-01;
  a52=arg[2]? arg[2][120] : 0;
  a52=(a2*a52);
  a14=arg[2]? arg[2][18] : 0;
  a45=arg[2]? arg[2][16] : 0;
  a82=arg[2]? arg[2][19] : 0;
  a83=2.0000000000000001e-01;
  a84=(a83*a16);
  a85=(a84/a11);
  a85=(a82*a85);
  a85=(a45-a85);
  a85=(a85/a45);
  a86=arg[2]? arg[2][13] : 0;
  a87=(a86/a82);
  a88=arg[2]? arg[2][15] : 0;
  a87=(a87/a88);
  a87=(a87-a0);
  a85=pow(a85,a87);
  a85=(a14*a85);
  a85=(a52*a85);
  a89=arg[2]? arg[2][26] : 0;
  a90=4.3429448190325176e-01;
  a91=(a84/a11);
  a91=casadi_sq(a91);
  a91=(a91+a0);
  a91=sqrt(a91);
  a92=arg[2]? arg[2][24] : 0;
  a91=(a91/a92);
  a91=log(a91);
  a91=(a90*a91);
  a91=(a89*a91);
  a93=arg[2]? arg[2][23] : 0;
  a94=(a93/a92);
  a94=log(a94);
  a94=(a90*a94);
  a91=(a91/a94);
  a95=(a83*a32);
  a95=(a95/a11);
  a91=(a91-a95);
  a95=casadi_sq(a91);
  a96=(a83*a50);
  a96=(a96/a11);
  a97=casadi_sq(a96);
  a95=(a95+a97);
  a97=(a83*a51);
  a97=(a97/a11);
  a98=casadi_sq(a97);
  a95=(a95+a98);
  a98=9.9999999999999998e-13;
  a95=(a95+a98);
  a95=sqrt(a95);
  a85=(a85*a95);
  a85=(a85*a10);
  a95=(a83*a1);
  a99=casadi_sq(a95);
  a100=(a83*a20);
  a101=casadi_sq(a100);
  a99=(a99+a101);
  a101=casadi_sq(a84);
  a99=(a99+a101);
  a101=casadi_sq(a91);
  a102=casadi_sq(a96);
  a101=(a101+a102);
  a102=casadi_sq(a97);
  a101=(a101+a102);
  a101=(a101+a98);
  a101=sqrt(a101);
  a102=(a91/a101);
  a95=(a95*a102);
  a102=(a96/a101);
  a100=(a100*a102);
  a95=(a95-a100);
  a101=(a97/a101);
  a84=(a84*a101);
  a95=(a95-a84);
  a95=casadi_sq(a95);
  a99=(a99-a95);
  a99=(a99+a98);
  a99=sqrt(a99);
  a85=(a85*a99);
  a91=(a85*a91);
  a91=(a3*a91);
  a99=3.0000000000000004e-01;
  a95=4.0000000000000002e-01;
  a84=(a95*a16);
  a101=(a83*a16);
  a100=(a84+a101);
  a100=(a100/a11);
  a100=(a82*a100);
  a100=(a45-a100);
  a100=(a100/a45);
  a100=pow(a100,a87);
  a100=(a14*a100);
  a100=(a52*a100);
  a102=(a84+a101);
  a102=(a102/a11);
  a102=casadi_sq(a102);
  a102=(a102+a0);
  a102=sqrt(a102);
  a102=(a102/a92);
  a102=log(a102);
  a102=(a90*a102);
  a102=(a89*a102);
  a102=(a102/a94);
  a103=(a95*a32);
  a104=(a83*a32);
  a103=(a103+a104);
  a103=(a103/a11);
  a102=(a102-a103);
  a103=casadi_sq(a102);
  a104=(a95*a50);
  a105=(a83*a50);
  a104=(a104+a105);
  a104=(a104/a11);
  a105=casadi_sq(a104);
  a103=(a103+a105);
  a105=(a95*a51);
  a106=(a83*a51);
  a105=(a105+a106);
  a105=(a105/a11);
  a106=casadi_sq(a105);
  a103=(a103+a106);
  a103=(a103+a98);
  a103=sqrt(a103);
  a100=(a100*a103);
  a100=(a100*a10);
  a103=(a95*a1);
  a106=(a83*a1);
  a103=(a103-a106);
  a106=casadi_sq(a103);
  a107=(a95*a20);
  a83=(a83*a20);
  a107=(a107-a83);
  a83=casadi_sq(a107);
  a106=(a106+a83);
  a84=(a84-a101);
  a101=casadi_sq(a84);
  a106=(a106+a101);
  a101=casadi_sq(a102);
  a83=casadi_sq(a104);
  a101=(a101+a83);
  a83=casadi_sq(a105);
  a101=(a101+a83);
  a101=(a101+a98);
  a101=sqrt(a101);
  a83=(a102/a101);
  a103=(a103*a83);
  a83=(a104/a101);
  a107=(a107*a83);
  a103=(a103-a107);
  a101=(a105/a101);
  a84=(a84*a101);
  a103=(a103-a84);
  a103=casadi_sq(a103);
  a106=(a106-a103);
  a106=(a106+a98);
  a106=sqrt(a106);
  a100=(a100*a106);
  a102=(a100*a102);
  a102=(a99*a102);
  a91=(a91+a102);
  a102=5.9999999999999998e-01;
  a106=(a102*a16);
  a103=(a95*a16);
  a84=(a106+a103);
  a84=(a84/a11);
  a84=(a82*a84);
  a84=(a45-a84);
  a84=(a84/a45);
  a84=pow(a84,a87);
  a84=(a14*a84);
  a84=(a52*a84);
  a101=(a106+a103);
  a101=(a101/a11);
  a101=casadi_sq(a101);
  a101=(a101+a0);
  a101=sqrt(a101);
  a101=(a101/a92);
  a101=log(a101);
  a101=(a90*a101);
  a101=(a89*a101);
  a101=(a101/a94);
  a107=(a102*a32);
  a83=(a95*a32);
  a107=(a107+a83);
  a107=(a107/a11);
  a101=(a101-a107);
  a107=casadi_sq(a101);
  a83=(a102*a50);
  a108=(a95*a50);
  a83=(a83+a108);
  a83=(a83/a11);
  a108=casadi_sq(a83);
  a107=(a107+a108);
  a108=(a102*a51);
  a109=(a95*a51);
  a108=(a108+a109);
  a108=(a108/a11);
  a109=casadi_sq(a108);
  a107=(a107+a109);
  a107=(a107+a98);
  a107=sqrt(a107);
  a84=(a84*a107);
  a84=(a84*a10);
  a107=(a102*a1);
  a109=(a95*a1);
  a107=(a107-a109);
  a109=casadi_sq(a107);
  a110=(a102*a20);
  a95=(a95*a20);
  a110=(a110-a95);
  a95=casadi_sq(a110);
  a109=(a109+a95);
  a106=(a106-a103);
  a103=casadi_sq(a106);
  a109=(a109+a103);
  a103=casadi_sq(a101);
  a95=casadi_sq(a83);
  a103=(a103+a95);
  a95=casadi_sq(a108);
  a103=(a103+a95);
  a103=(a103+a98);
  a103=sqrt(a103);
  a95=(a101/a103);
  a107=(a107*a95);
  a95=(a83/a103);
  a110=(a110*a95);
  a107=(a107-a110);
  a103=(a108/a103);
  a106=(a106*a103);
  a107=(a107-a106);
  a107=casadi_sq(a107);
  a109=(a109-a107);
  a109=(a109+a98);
  a109=sqrt(a109);
  a84=(a84*a109);
  a101=(a84*a101);
  a101=(a2*a101);
  a91=(a91+a101);
  a101=7.0000000000000007e-01;
  a109=8.0000000000000004e-01;
  a107=(a109*a16);
  a106=(a102*a16);
  a103=(a107+a106);
  a103=(a103/a11);
  a103=(a82*a103);
  a103=(a45-a103);
  a103=(a103/a45);
  a103=pow(a103,a87);
  a103=(a14*a103);
  a103=(a52*a103);
  a110=(a107+a106);
  a110=(a110/a11);
  a110=casadi_sq(a110);
  a110=(a110+a0);
  a110=sqrt(a110);
  a110=(a110/a92);
  a110=log(a110);
  a110=(a90*a110);
  a110=(a89*a110);
  a110=(a110/a94);
  a95=(a109*a32);
  a111=(a102*a32);
  a95=(a95+a111);
  a95=(a95/a11);
  a110=(a110-a95);
  a95=casadi_sq(a110);
  a111=(a109*a50);
  a112=(a102*a50);
  a111=(a111+a112);
  a111=(a111/a11);
  a112=casadi_sq(a111);
  a95=(a95+a112);
  a112=(a109*a51);
  a113=(a102*a51);
  a112=(a112+a113);
  a112=(a112/a11);
  a113=casadi_sq(a112);
  a95=(a95+a113);
  a95=(a95+a98);
  a95=sqrt(a95);
  a103=(a103*a95);
  a103=(a103*a10);
  a95=(a109*a1);
  a113=(a102*a1);
  a95=(a95-a113);
  a113=casadi_sq(a95);
  a114=(a109*a20);
  a102=(a102*a20);
  a114=(a114-a102);
  a102=casadi_sq(a114);
  a113=(a113+a102);
  a107=(a107-a106);
  a106=casadi_sq(a107);
  a113=(a113+a106);
  a106=casadi_sq(a110);
  a102=casadi_sq(a111);
  a106=(a106+a102);
  a102=casadi_sq(a112);
  a106=(a106+a102);
  a106=(a106+a98);
  a106=sqrt(a106);
  a102=(a110/a106);
  a95=(a95*a102);
  a102=(a111/a106);
  a114=(a114*a102);
  a95=(a95-a114);
  a106=(a112/a106);
  a107=(a107*a106);
  a95=(a95-a107);
  a95=casadi_sq(a95);
  a113=(a113-a95);
  a113=(a113+a98);
  a113=sqrt(a113);
  a103=(a103*a113);
  a110=(a103*a110);
  a110=(a101*a110);
  a91=(a91+a110);
  a110=9.0000000000000002e-01;
  a113=(a109*a16);
  a95=(a16+a113);
  a95=(a95/a11);
  a95=(a82*a95);
  a95=(a45-a95);
  a95=(a95/a45);
  a95=pow(a95,a87);
  a95=(a14*a95);
  a52=(a52*a95);
  a95=(a16+a113);
  a95=(a95/a11);
  a95=casadi_sq(a95);
  a95=(a95+a0);
  a95=sqrt(a95);
  a95=(a95/a92);
  a95=log(a95);
  a95=(a90*a95);
  a95=(a89*a95);
  a95=(a95/a94);
  a94=(a109*a32);
  a94=(a32+a94);
  a94=(a94/a11);
  a95=(a95-a94);
  a94=casadi_sq(a95);
  a87=(a109*a50);
  a87=(a50+a87);
  a87=(a87/a11);
  a107=casadi_sq(a87);
  a94=(a94+a107);
  a107=(a109*a51);
  a107=(a51+a107);
  a107=(a107/a11);
  a106=casadi_sq(a107);
  a94=(a94+a106);
  a94=(a94+a98);
  a94=sqrt(a94);
  a52=(a52*a94);
  a52=(a52*a10);
  a10=(a109*a1);
  a10=(a1-a10);
  a94=casadi_sq(a10);
  a109=(a109*a20);
  a109=(a20-a109);
  a106=casadi_sq(a109);
  a94=(a94+a106);
  a113=(a16-a113);
  a106=casadi_sq(a113);
  a94=(a94+a106);
  a106=casadi_sq(a95);
  a114=casadi_sq(a87);
  a106=(a106+a114);
  a114=casadi_sq(a107);
  a106=(a106+a114);
  a106=(a106+a98);
  a106=sqrt(a106);
  a114=(a95/a106);
  a10=(a10*a114);
  a114=(a87/a106);
  a109=(a109*a114);
  a10=(a10-a109);
  a106=(a107/a106);
  a113=(a113*a106);
  a10=(a10-a113);
  a10=casadi_sq(a10);
  a94=(a94-a10);
  a94=(a94+a98);
  a94=sqrt(a94);
  a52=(a52*a94);
  a95=(a52*a95);
  a95=(a110*a95);
  a91=(a91+a95);
  a95=arg[2]? arg[2][144] : 0;
  a94=arg[2]? arg[2][0] : 0;
  a94=(a15*a94);
  a94=(a95*a94);
  a98=(a0-a95);
  a10=arg[1]? arg[1][12] : 0;
  a113=arg[2]? arg[2][64] : 0;
  a106=arg[1]? arg[1][18] : 0;
  a113=(a113*a106);
  a109=arg[2]? arg[2][65] : 0;
  a114=casadi_sq(a16);
  a114=(a114+a0);
  a114=sqrt(a114);
  a114=(a114/a92);
  a114=log(a114);
  a114=(a90*a114);
  a89=(a89*a114);
  a93=(a93/a92);
  a93=log(a93);
  a90=(a90*a93);
  a89=(a89/a90);
  a89=(a89-a32);
  a90=arg[1]? arg[1][15] : 0;
  a93=(a89*a90);
  a92=arg[1]? arg[1][16] : 0;
  a114=(a50*a92);
  a93=(a93-a114);
  a114=arg[1]? arg[1][17] : 0;
  a102=(a51*a114);
  a93=(a93-a102);
  a102=arg[1]? arg[1][9] : 0;
  a115=(a89*a102);
  a116=arg[1]? arg[1][10] : 0;
  a117=(a50*a116);
  a115=(a115-a117);
  a117=arg[1]? arg[1][11] : 0;
  a118=(a51*a117);
  a115=(a115-a118);
  a115=casadi_sq(a115);
  a118=1.0000000000000001e-16;
  a115=(a115+a118);
  a115=sqrt(a115);
  a93=(a93/a115);
  a115=(a106*a93);
  a109=(a109*a115);
  a113=(a113+a109);
  a109=arg[2]? arg[2][66] : 0;
  a115=casadi_sq(a93);
  a115=(a106*a115);
  a109=(a109*a115);
  a113=(a113+a109);
  a109=arg[2]? arg[2][55] : 0;
  a115=(a89*a10);
  a119=arg[1]? arg[1][13] : 0;
  a120=(a50*a119);
  a115=(a115-a120);
  a120=arg[1]? arg[1][14] : 0;
  a121=(a51*a120);
  a115=(a115-a121);
  a121=(a89*a102);
  a122=(a50*a116);
  a121=(a121-a122);
  a122=(a51*a117);
  a121=(a121-a122);
  a121=casadi_sq(a121);
  a121=(a121+a118);
  a121=sqrt(a121);
  a115=(a115/a121);
  a109=(a109*a115);
  a121=arg[2]? arg[2][56] : 0;
  a118=(a115*a93);
  a121=(a121*a118);
  a109=(a109+a121);
  a121=arg[2]? arg[2][57] : 0;
  a118=casadi_sq(a93);
  a118=(a115*a118);
  a121=(a121*a118);
  a109=(a109+a121);
  a121=arg[2]? arg[2][58] : 0;
  a118=arg[1]? arg[1][6] : 0;
  a122=casadi_sq(a89);
  a123=casadi_sq(a50);
  a122=(a122+a123);
  a123=casadi_sq(a51);
  a122=(a122+a123);
  a122=sqrt(a122);
  a122=(a11*a122);
  a123=(a118/a122);
  a124=arg[2]? arg[2][127] : 0;
  a123=(a123*a124);
  a121=(a121*a123);
  a125=arg[2]? arg[2][59] : 0;
  a126=(a123*a93);
  a125=(a125*a126);
  a121=(a121+a125);
  a125=arg[2]? arg[2][60] : 0;
  a126=casadi_sq(a93);
  a126=(a123*a126);
  a125=(a125*a126);
  a121=(a121+a125);
  a109=(a109+a121);
  a121=arg[2]? arg[2][61] : 0;
  a125=arg[1]? arg[1][8] : 0;
  a126=(a125/a122);
  a126=(a126*a124);
  a121=(a121*a126);
  a127=arg[2]? arg[2][62] : 0;
  a128=(a126*a93);
  a127=(a127*a128);
  a121=(a121+a127);
  a127=arg[2]? arg[2][63] : 0;
  a128=casadi_sq(a93);
  a128=(a126*a128);
  a127=(a127*a128);
  a121=(a121+a127);
  a109=(a109+a121);
  a113=(a113-a109);
  a109=arg[2]? arg[2][67] : 0;
  a121=arg[1]? arg[1][20] : 0;
  a109=(a109*a121);
  a127=arg[2]? arg[2][68] : 0;
  a128=(a121*a93);
  a127=(a127*a128);
  a109=(a109+a127);
  a127=arg[2]? arg[2][69] : 0;
  a128=casadi_sq(a93);
  a128=(a121*a128);
  a127=(a127*a128);
  a109=(a109+a127);
  a113=(a113+a109);
  a109=(a82*a16);
  a109=(a45-a109);
  a109=(a109/a45);
  a82=(a86/a82);
  a82=(a82/a88);
  a82=(a82-a0);
  a109=pow(a109,a82);
  a14=(a14*a109);
  a14=(a2*a14);
  a89=casadi_sq(a89);
  a109=casadi_sq(a50);
  a89=(a89+a109);
  a109=casadi_sq(a51);
  a89=(a89+a109);
  a14=(a14*a89);
  a113=(a113*a14);
  a89=arg[2]? arg[2][128] : 0;
  a113=(a113*a89);
  a109=(a10*a113);
  a82=arg[2]? arg[2][46] : 0;
  a88=arg[2]? arg[2][47] : 0;
  a88=(a88*a93);
  a45=arg[2]? arg[2][48] : 0;
  a127=casadi_sq(a93);
  a45=(a45*a127);
  a88=(a88+a45);
  a82=(a82+a88);
  a88=arg[2]? arg[2][49] : 0;
  a45=arg[1]? arg[1][7] : 0;
  a122=(a45/a122);
  a127=arg[2]? arg[2][129] : 0;
  a122=(a122*a127);
  a88=(a88*a122);
  a128=arg[2]? arg[2][50] : 0;
  a129=(a122*a93);
  a128=(a128*a129);
  a88=(a88+a128);
  a128=arg[2]? arg[2][51] : 0;
  a129=casadi_sq(a93);
  a129=(a122*a129);
  a128=(a128*a129);
  a88=(a88+a128);
  a82=(a82+a88);
  a88=arg[2]? arg[2][52] : 0;
  a128=arg[1]? arg[1][19] : 0;
  a88=(a88*a128);
  a129=arg[2]? arg[2][53] : 0;
  a130=(a128*a93);
  a129=(a129*a130);
  a88=(a88+a129);
  a129=arg[2]? arg[2][54] : 0;
  a130=casadi_sq(a93);
  a130=(a128*a130);
  a129=(a129*a130);
  a88=(a88+a129);
  a82=(a82+a88);
  a82=(a82*a14);
  a82=(a82*a89);
  a88=(a102*a82);
  a109=(a109-a88);
  a88=arg[2]? arg[2][70] : 0;
  a129=arg[2]? arg[2][71] : 0;
  a129=(a129*a93);
  a130=arg[2]? arg[2][72] : 0;
  a131=casadi_sq(a93);
  a130=(a130*a131);
  a129=(a129+a130);
  a88=(a88+a129);
  a129=arg[2]? arg[2][73] : 0;
  a129=(a129*a122);
  a130=arg[2]? arg[2][74] : 0;
  a131=(a122*a93);
  a130=(a130*a131);
  a129=(a129+a130);
  a130=arg[2]? arg[2][75] : 0;
  a131=casadi_sq(a93);
  a131=(a122*a131);
  a130=(a130*a131);
  a129=(a129+a130);
  a88=(a88+a129);
  a129=arg[2]? arg[2][76] : 0;
  a129=(a129*a128);
  a130=arg[2]? arg[2][77] : 0;
  a131=(a128*a93);
  a130=(a130*a131);
  a129=(a129+a130);
  a130=arg[2]? arg[2][78] : 0;
  a131=casadi_sq(a93);
  a131=(a128*a131);
  a130=(a130*a131);
  a129=(a129+a130);
  a88=(a88+a129);
  a88=(a88*a14);
  a88=(a88*a89);
  a129=(a90*a88);
  a109=(a109-a129);
  a109=(a98*a109);
  a94=(a94+a109);
  a91=(a91+a94);
  a9=(a4*a9);
  a9=(a9*a65);
  a94=(a9*a32);
  a91=(a91+a94);
  a7=(a7-a91);
  a7=(a7/a12);
  if (res[1]!=0) res[1][0]=a7;
  a24=(a24*a34);
  a29=(a29*a48);
  a24=(a24+a29);
  a33=(a33*a28);
  a24=(a24+a33);
  a68=(a68*a53);
  a71=(a13*a71);
  a68=(a68-a71);
  a71=(a20*a61);
  a68=(a68-a71);
  a71=(a21*a63);
  a58=(a69*a58);
  a71=(a71-a58);
  a68=(a68+a71);
  a71=(a50+a50);
  a71=(a71*a53);
  a68=(a68+a71);
  a68=(a68*a65);
  a24=(a24+a68);
  a68=(a20*a54);
  a72=(a13*a72);
  a68=(a68+a72);
  a72=(a21*a75);
  a68=(a68+a72);
  a68=(a68*a32);
  a72=(a20*a73);
  a72=(a62+a72);
  a79=(a13*a79);
  a72=(a72+a79);
  a79=(a69/a5);
  a71=(a21*a78);
  a79=(a79+a71);
  a72=(a72+a79);
  a72=(a72*a50);
  a68=(a68+a72);
  a72=(a20*a57);
  a70=(a13*a70);
  a72=(a72+a70);
  a21=(a21*a66);
  a72=(a72+a21);
  a72=(a72*a51);
  a68=(a68+a72);
  a24=(a24+a68);
  a68=(a50*a60);
  a46=(a46*a55);
  a68=(a68-a46);
  a81=(a49*a81);
  a46=(a50*a56);
  a81=(a81+a46);
  a81=(a81/a5);
  a68=(a68+a81);
  a24=(a24-a68);
  a68=arg[2]? arg[2][1] : 0;
  a68=(a15*a68);
  a68=(a95*a68);
  a81=(a119*a113);
  a46=(a116*a82);
  a81=(a81-a46);
  a46=(a92*a88);
  a81=(a81-a46);
  a81=(a98*a81);
  a68=(a68+a81);
  a96=(a85*a96);
  a96=(a3*a96);
  a104=(a100*a104);
  a104=(a99*a104);
  a96=(a96+a104);
  a83=(a84*a83);
  a83=(a2*a83);
  a96=(a96+a83);
  a111=(a103*a111);
  a111=(a101*a111);
  a96=(a96+a111);
  a87=(a52*a87);
  a87=(a110*a87);
  a96=(a96+a87);
  a68=(a68-a96);
  a96=(a9*a50);
  a68=(a68+a96);
  a24=(a24-a68);
  a24=(a24/a22);
  if (res[1]!=0) res[1][1]=a24;
  a6=(a6*a34);
  a27=(a27*a48);
  a6=(a6+a27);
  a30=(a30*a28);
  a6=(a6+a30);
  a64=(a64*a53);
  a67=(a13*a67);
  a64=(a64-a67);
  a61=(a16*a61);
  a64=(a64-a61);
  a63=(a17*a63);
  a59=(a69*a59);
  a63=(a63-a59);
  a64=(a64+a63);
  a63=(a51+a51);
  a63=(a63*a53);
  a64=(a64+a63);
  a64=(a64*a65);
  a6=(a6+a64);
  a54=(a16*a54);
  a74=(a13*a74);
  a54=(a54+a74);
  a75=(a17*a75);
  a54=(a54+a75);
  a54=(a54*a32);
  a73=(a16*a73);
  a77=(a13*a77);
  a73=(a73+a77);
  a78=(a17*a78);
  a73=(a73+a78);
  a73=(a73*a50);
  a54=(a54+a73);
  a57=(a16*a57);
  a62=(a62+a57);
  a13=(a13*a80);
  a62=(a62+a13);
  a69=(a69/a5);
  a17=(a17*a66);
  a69=(a69+a17);
  a62=(a62+a69);
  a62=(a62*a51);
  a54=(a54+a62);
  a6=(a6+a54);
  a60=(a51*a60);
  a47=(a47*a55);
  a86=(a86*a8);
  a47=(a47+a86);
  a60=(a60-a47);
  a49=(a49*a76);
  a56=(a51*a56);
  a49=(a49+a56);
  a49=(a49/a5);
  a60=(a60+a49);
  a6=(a6-a60);
  a60=arg[2]? arg[2][2] : 0;
  a15=(a15*a60);
  a15=(a95*a15);
  a113=(a120*a113);
  a82=(a117*a82);
  a113=(a113-a82);
  a88=(a114*a88);
  a113=(a113-a88);
  a98=(a98*a113);
  a15=(a15+a98);
  a85=(a85*a97);
  a3=(a3*a85);
  a100=(a100*a105);
  a99=(a99*a100);
  a3=(a3+a99);
  a84=(a84*a108);
  a84=(a2*a84);
  a3=(a3+a84);
  a103=(a103*a112);
  a101=(a101*a103);
  a3=(a3+a101);
  a52=(a52*a107);
  a110=(a110*a52);
  a3=(a3+a110);
  a15=(a15-a3);
  a9=(a9*a51);
  a15=(a15+a9);
  a6=(a6-a15);
  a6=(a6/a23);
  if (res[1]!=0) res[1][2]=a6;
  a6=1.4342928478200000e+06;
  a23=arg[2]? arg[2][3] : 0;
  a23=(a6*a23);
  a23=(a95*a23);
  a15=(a0-a95);
  a14=(a14*a89);
  a89=arg[2]? arg[2][45] : 0;
  a9=arg[2]? arg[2][88] : 0;
  a9=(a9*a106);
  a3=arg[2]? arg[2][89] : 0;
  a110=(a106*a93);
  a3=(a3*a110);
  a9=(a9+a3);
  a3=arg[2]? arg[2][90] : 0;
  a110=casadi_sq(a93);
  a110=(a106*a110);
  a3=(a3*a110);
  a9=(a9+a3);
  a9=(a89*a9);
  a3=arg[2]? arg[2][79] : 0;
  a3=(a3*a115);
  a110=arg[2]? arg[2][80] : 0;
  a52=(a115*a93);
  a110=(a110*a52);
  a3=(a3+a110);
  a110=arg[2]? arg[2][81] : 0;
  a52=casadi_sq(a93);
  a52=(a115*a52);
  a110=(a110*a52);
  a3=(a3+a110);
  a110=arg[2]? arg[2][82] : 0;
  a110=(a110*a123);
  a52=arg[2]? arg[2][83] : 0;
  a107=(a123*a93);
  a52=(a52*a107);
  a110=(a110+a52);
  a52=arg[2]? arg[2][84] : 0;
  a107=casadi_sq(a93);
  a107=(a123*a107);
  a52=(a52*a107);
  a110=(a110+a52);
  a3=(a3+a110);
  a110=arg[2]? arg[2][85] : 0;
  a110=(a110*a126);
  a52=arg[2]? arg[2][86] : 0;
  a107=(a126*a93);
  a52=(a52*a107);
  a110=(a110+a52);
  a52=arg[2]? arg[2][87] : 0;
  a107=casadi_sq(a93);
  a107=(a126*a107);
  a52=(a52*a107);
  a110=(a110+a52);
  a3=(a3+a110);
  a9=(a9-a3);
  a3=arg[2]? arg[2][91] : 0;
  a3=(a3*a121);
  a110=arg[2]? arg[2][92] : 0;
  a52=(a121*a93);
  a110=(a110*a52);
  a3=(a3+a110);
  a110=arg[2]? arg[2][93] : 0;
  a52=casadi_sq(a93);
  a52=(a121*a52);
  a110=(a110*a52);
  a3=(a3+a110);
  a3=(a89*a3);
  a9=(a9+a3);
  a9=(a124*a9);
  a9=(a14*a9);
  a9=(a15*a9);
  a23=(a23-a9);
  a9=arg[0]? arg[0][6] : 0;
  a3=(a36*a9);
  a110=arg[0]? arg[0][7] : 0;
  a52=(a39*a110);
  a3=(a3+a52);
  a52=arg[0]? arg[0][8] : 0;
  a107=(a42*a52);
  a3=(a3+a107);
  a107=(a38*a118);
  a101=(a41*a45);
  a107=(a107+a101);
  a101=(a44*a125);
  a107=(a107+a101);
  a101=(a45*a107);
  a103=(a37*a118);
  a112=(a40*a45);
  a103=(a103+a112);
  a112=(a43*a125);
  a103=(a103+a112);
  a112=(a125*a103);
  a101=(a101-a112);
  a3=(a3+a101);
  a23=(a23-a3);
  a23=(a23/a6);
  if (res[1]!=0) res[1][3]=a23;
  a23=arg[2]? arg[2][4] : 0;
  a23=(a6*a23);
  a23=(a95*a23);
  a3=arg[2]? arg[2][94] : 0;
  a101=arg[2]? arg[2][95] : 0;
  a101=(a101*a93);
  a112=arg[2]? arg[2][96] : 0;
  a84=casadi_sq(a93);
  a112=(a112*a84);
  a101=(a101+a112);
  a3=(a3+a101);
  a101=arg[2]? arg[2][97] : 0;
  a101=(a101*a122);
  a112=arg[2]? arg[2][98] : 0;
  a84=(a122*a93);
  a112=(a112*a84);
  a101=(a101+a112);
  a112=arg[2]? arg[2][99] : 0;
  a84=casadi_sq(a93);
  a122=(a122*a84);
  a112=(a112*a122);
  a101=(a101+a112);
  a3=(a3+a101);
  a101=arg[2]? arg[2][100] : 0;
  a101=(a101*a128);
  a112=arg[2]? arg[2][101] : 0;
  a122=(a128*a93);
  a112=(a112*a122);
  a101=(a101+a112);
  a112=arg[2]? arg[2][102] : 0;
  a122=casadi_sq(a93);
  a128=(a128*a122);
  a112=(a112*a128);
  a101=(a101+a112);
  a101=(a89*a101);
  a3=(a3+a101);
  a127=(a127*a3);
  a127=(a14*a127);
  a127=(a15*a127);
  a23=(a23+a127);
  a37=(a37*a9);
  a40=(a40*a110);
  a37=(a37+a40);
  a43=(a43*a52);
  a37=(a37+a43);
  a107=(a118*a107);
  a36=(a36*a118);
  a39=(a39*a45);
  a36=(a36+a39);
  a42=(a42*a125);
  a36=(a36+a42);
  a42=(a125*a36);
  a107=(a107-a42);
  a37=(a37-a107);
  a23=(a23-a37);
  a23=(a23/a6);
  if (res[1]!=0) res[1][4]=a23;
  a23=arg[2]? arg[2][5] : 0;
  a23=(a6*a23);
  a95=(a95*a23);
  a23=arg[2]? arg[2][112] : 0;
  a23=(a23*a106);
  a37=arg[2]? arg[2][113] : 0;
  a107=(a106*a93);
  a37=(a37*a107);
  a23=(a23+a37);
  a37=arg[2]? arg[2][114] : 0;
  a107=casadi_sq(a93);
  a106=(a106*a107);
  a37=(a37*a106);
  a23=(a23+a37);
  a23=(a89*a23);
  a37=arg[2]? arg[2][103] : 0;
  a37=(a37*a115);
  a106=arg[2]? arg[2][104] : 0;
  a107=(a115*a93);
  a106=(a106*a107);
  a37=(a37+a106);
  a106=arg[2]? arg[2][105] : 0;
  a107=casadi_sq(a93);
  a115=(a115*a107);
  a106=(a106*a115);
  a37=(a37+a106);
  a106=arg[2]? arg[2][106] : 0;
  a106=(a106*a123);
  a115=arg[2]? arg[2][107] : 0;
  a107=(a123*a93);
  a115=(a115*a107);
  a106=(a106+a115);
  a115=arg[2]? arg[2][108] : 0;
  a107=casadi_sq(a93);
  a123=(a123*a107);
  a115=(a115*a123);
  a106=(a106+a115);
  a37=(a37+a106);
  a106=arg[2]? arg[2][109] : 0;
  a106=(a106*a126);
  a115=arg[2]? arg[2][110] : 0;
  a123=(a126*a93);
  a115=(a115*a123);
  a106=(a106+a115);
  a115=arg[2]? arg[2][111] : 0;
  a123=casadi_sq(a93);
  a126=(a126*a123);
  a115=(a115*a126);
  a106=(a106+a115);
  a37=(a37+a106);
  a23=(a23-a37);
  a37=arg[2]? arg[2][115] : 0;
  a37=(a37*a121);
  a106=arg[2]? arg[2][116] : 0;
  a115=(a121*a93);
  a106=(a106*a115);
  a37=(a37+a106);
  a106=arg[2]? arg[2][117] : 0;
  a93=casadi_sq(a93);
  a121=(a121*a93);
  a106=(a106*a121);
  a37=(a37+a106);
  a89=(a89*a37);
  a23=(a23+a89);
  a124=(a124*a23);
  a14=(a14*a124);
  a15=(a15*a14);
  a95=(a95-a15);
  a38=(a38*a9);
  a41=(a41*a110);
  a38=(a38+a41);
  a44=(a44*a52);
  a38=(a38+a44);
  a103=(a118*a103);
  a36=(a45*a36);
  a103=(a103-a36);
  a38=(a38+a103);
  a95=(a95-a38);
  a95=(a95/a6);
  if (res[1]!=0) res[1][5]=a95;
  a95=arg[0]? arg[0][9] : 0;
  a6=arg[2]? arg[2][124] : 0;
  a6=(a6/a11);
  a38=casadi_sq(a102);
  a103=casadi_sq(a116);
  a38=(a38+a103);
  a103=casadi_sq(a117);
  a38=(a38+a103);
  a38=(a0-a38);
  a38=(a6*a38);
  a103=(a102*a38);
  a36=(a10*a102);
  a44=(a119*a116);
  a36=(a36+a44);
  a44=(a120*a117);
  a36=(a36+a44);
  a36=(a6*a36);
  a36=(a125-a36);
  a44=(a10*a36);
  a103=(a103+a44);
  a44=(a90*a102);
  a52=(a92*a116);
  a44=(a44+a52);
  a52=(a114*a117);
  a44=(a44+a52);
  a44=(a6*a44);
  a44=(a44+a45);
  a52=(a90*a44);
  a103=(a103-a52);
  a95=(a95-a103);
  if (res[1]!=0) res[1][6]=a95;
  a95=arg[0]? arg[0][10] : 0;
  a103=(a116*a38);
  a52=(a119*a36);
  a103=(a103+a52);
  a52=(a92*a44);
  a103=(a103-a52);
  a95=(a95-a103);
  if (res[1]!=0) res[1][7]=a95;
  a95=arg[0]? arg[0][11] : 0;
  a38=(a117*a38);
  a36=(a120*a36);
  a38=(a38+a36);
  a44=(a114*a44);
  a38=(a38-a44);
  a95=(a95-a38);
  if (res[1]!=0) res[1][8]=a95;
  a95=arg[0]? arg[0][12] : 0;
  a38=casadi_sq(a10);
  a44=casadi_sq(a119);
  a38=(a38+a44);
  a44=casadi_sq(a120);
  a38=(a38+a44);
  a38=(a0-a38);
  a38=(a6*a38);
  a44=(a10*a38);
  a36=(a102*a10);
  a103=(a116*a119);
  a36=(a36+a103);
  a103=(a117*a120);
  a36=(a36+a103);
  a36=(a6*a36);
  a36=(a36+a125);
  a125=(a102*a36);
  a44=(a44-a125);
  a125=(a90*a10);
  a103=(a92*a119);
  a125=(a125+a103);
  a103=(a114*a120);
  a125=(a125+a103);
  a125=(a6*a125);
  a125=(a118-a125);
  a103=(a90*a125);
  a44=(a44+a103);
  a95=(a95-a44);
  if (res[1]!=0) res[1][9]=a95;
  a95=arg[0]? arg[0][13] : 0;
  a44=(a119*a38);
  a103=(a116*a36);
  a44=(a44-a103);
  a103=(a92*a125);
  a44=(a44+a103);
  a95=(a95-a44);
  if (res[1]!=0) res[1][10]=a95;
  a95=arg[0]? arg[0][14] : 0;
  a38=(a120*a38);
  a36=(a117*a36);
  a38=(a38-a36);
  a125=(a114*a125);
  a38=(a38+a125);
  a95=(a95-a38);
  if (res[1]!=0) res[1][11]=a95;
  a95=arg[0]? arg[0][15] : 0;
  a38=(a102*a90);
  a125=(a116*a92);
  a38=(a38+a125);
  a125=(a117*a114);
  a38=(a38+a125);
  a38=(a6*a38);
  a45=(a45-a38);
  a102=(a102*a45);
  a38=(a10*a90);
  a125=(a119*a92);
  a38=(a38+a125);
  a125=(a120*a114);
  a38=(a38+a125);
  a38=(a6*a38);
  a38=(a38+a118);
  a10=(a10*a38);
  a102=(a102-a10);
  a10=casadi_sq(a90);
  a118=casadi_sq(a92);
  a10=(a10+a118);
  a118=casadi_sq(a114);
  a10=(a10+a118);
  a0=(a0-a10);
  a6=(a6*a0);
  a90=(a90*a6);
  a102=(a102+a90);
  a95=(a95-a102);
  if (res[1]!=0) res[1][12]=a95;
  a95=arg[0]? arg[0][16] : 0;
  a116=(a116*a45);
  a119=(a119*a38);
  a116=(a116-a119);
  a92=(a92*a6);
  a116=(a116+a92);
  a95=(a95-a116);
  if (res[1]!=0) res[1][13]=a95;
  a95=arg[0]? arg[0][17] : 0;
  a117=(a117*a45);
  a120=(a120*a38);
  a117=(a117-a120);
  a114=(a114*a6);
  a117=(a117+a114);
  a95=(a95-a117);
  if (res[1]!=0) res[1][14]=a95;
  a95=arg[0]? arg[0][23] : 0;
  a117=arg[2]? arg[2][9] : 0;
  a95=(a95-a117);
  if (res[1]!=0) res[1][15]=a95;
  a95=arg[0]? arg[0][18] : 0;
  a117=arg[2]? arg[2][6] : 0;
  a95=(a95-a117);
  if (res[1]!=0) res[1][16]=a95;
  a95=arg[0]? arg[0][19] : 0;
  a117=arg[2]? arg[2][7] : 0;
  a95=(a95-a117);
  if (res[1]!=0) res[1][17]=a95;
  a95=arg[0]? arg[0][20] : 0;
  a117=arg[2]? arg[2][8] : 0;
  a95=(a95-a117);
  if (res[1]!=0) res[1][18]=a95;
  a95=arg[0]? arg[0][22] : 0;
  a117=arg[1]? arg[1][23] : 0;
  a95=(a95-a117);
  if (res[1]!=0) res[1][19]=a95;
  a95=arg[0]? arg[0][21] : 0;
  a95=(a95-a65);
  if (res[1]!=0) res[1][20]=a95;
  a95=arg[0]? arg[0][0] : 0;
  a95=(a95-a32);
  if (res[1]!=0) res[1][21]=a95;
  a95=arg[0]? arg[0][1] : 0;
  a95=(a95-a50);
  if (res[1]!=0) res[1][22]=a95;
  a95=arg[0]? arg[0][2] : 0;
  a95=(a95-a51);
  if (res[1]!=0) res[1][23]=a95;
  a34=(a19*a34);
  a48=(a31*a48);
  a34=(a34+a48);
  a28=(a35*a28);
  a34=(a34+a28);
  a28=(a5+a5);
  a4=(a4*a28);
  a4=(a2*a4);
  a117=(a4*a117);
  a34=(a34-a117);
  a25=(a25*a65);
  a25=(a25*a65);
  a34=(a34-a25);
  a25=casadi_sq(a32);
  a117=casadi_sq(a50);
  a25=(a25+a117);
  a117=casadi_sq(a51);
  a25=(a25+a117);
  a34=(a34+a25);
  a11=(a11*a26);
  a19=(a19*a32);
  a31=(a31*a50);
  a19=(a19+a31);
  a35=(a35*a51);
  a19=(a19+a35);
  a4=(a4*a65);
  a19=(a19-a4);
  a11=(a11*a19);
  a34=(a34+a11);
  a26=casadi_sq(a26);
  a1=casadi_sq(a1);
  a20=casadi_sq(a20);
  a1=(a1+a20);
  a16=casadi_sq(a16);
  a1=(a1+a16);
  a5=casadi_sq(a5);
  a1=(a1-a5);
  a2=(a2*a1);
  a26=(a26*a2);
  a34=(a34+a26);
  a34=(a34/a18);
  if (res[1]!=0) res[1][24]=a34;
  return 0;
}

/* G:(i0[25],i1[24],i2[151])->(o0[25]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int iter;
  struct casadi_newton_mem m;
  m.n = 25;
  m.abstol = 1e-12;
  m.abstol_step = 1e-12;
  m.x = w;
  m.g = w+25;
  m.jac_g_x = w+50;
  m.sp_a = casadi_s0;
  m.sp_v = casadi_s1;
  m.sp_r = casadi_s2;
  m.prinv = casadi_s3;
  m.pc = casadi_s4;
  m.lin_w = w+92;
  m.lin_v = w+142;
  m.lin_r = w+176;
  m.lin_beta = w+210;
  /* Get the initial guess */
  casadi_copy(arg[0], 25, m.x);
  for (iter=0; iter<1000; ++iter) {
    /* (re)calculate f and J */
    arg[3] = m.x;
    arg[4] = arg[1];
    arg[5] = arg[2];
    res[1] = m.jac_g_x;
    res[2] = m.g;
    if (casadi_f3(arg+3, res+1, iw, w+235, 0)) return 1;
    if (casadi_newton(&m)) break;
  }
  /* Get the solution */
  casadi_copy(m.x, 25, res[0]);
  return 0;
}

/* odef:(i0[24],i1[151],i2[25])->(o0[24]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[1]? arg[1][11] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[2]? arg[2][1] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[2]? arg[2][2] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[2]? arg[2][3] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[2]? arg[2][4] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[2]? arg[2][5] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[2]? arg[2][6] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[2]? arg[2][7] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[2]? arg[2][8] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[2]? arg[2][9] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[2]? arg[2][10] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][10]=a1;
  a1=arg[2]? arg[2][11] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][11]=a1;
  a1=arg[2]? arg[2][12] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][12]=a1;
  a1=arg[2]? arg[2][13] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][13]=a1;
  a1=arg[2]? arg[2][14] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][14]=a1;
  a1=arg[2]? arg[2][15] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][15]=a1;
  a1=arg[2]? arg[2][16] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][16]=a1;
  a1=arg[2]? arg[2][17] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][17]=a1;
  a1=arg[2]? arg[2][18] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][18]=a1;
  a1=arg[2]? arg[2][19] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][19]=a1;
  a1=arg[2]? arg[2][20] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][20]=a1;
  a1=arg[2]? arg[2][21] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][21]=a1;
  a1=arg[2]? arg[2][22] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][22]=a1;
  a1=arg[2]? arg[2][23] : 0;
  a0=(a0*a1);
  if (res[0]!=0) res[0][23]=a0;
  return 0;
}

/* quadf:(i0[24],i1[151],i2[25])->(o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[1]? arg[1][11] : 0;
  a1=1.9900297089545577e+02;
  a2=arg[2]? arg[2][24] : 0;
  a1=(a1*a2);
  a2=500.;
  a3=arg[0]? arg[0][21] : 0;
  a3=(a2*a3);
  a1=(a1*a3);
  a3=arg[0]? arg[0][22] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a2=7.2410659389423700e+06;
  a1=(a1/a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

/* F:(x0[24],z0[25],p[151])->(xf[24],zf[25],qf) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr;
  const casadi_real **arg1=arg+3, *cr, *cs;
  casadi_real *w0=w+417, w1, *w2=w+442, *w3=w+593, *w4=w+618, *w5=w+643, w6;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 24, w0);
  /* #1: @1 = 0.005 */
  w1 = 5.0000000000000001e-03;
  /* #2: @2 = input[2][0] */
  casadi_copy(arg[2], 151, w2);
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 25, w3);
  /* #4: @4 = G(@3, @0, @2) */
  arg1[0]=w3;
  arg1[1]=w0;
  arg1[2]=w2;
  res1[0]=w4;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @5 = odef(@0, @2, @4) */
  arg1[0]=w0;
  arg1[1]=w2;
  arg1[2]=w4;
  res1[0]=w5;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: @5 = (@1*@5) */
  for (i=0, rr=w5, cs=w5; i<24; ++i) (*rr++)  = (w1*(*cs++));
  /* #7: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<24; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #8: output[0][0] = @5 */
  casadi_copy(w5, 24, res[0]);
  /* #9: @3 = G(@4, @5, @2) */
  arg1[0]=w4;
  arg1[1]=w5;
  arg1[2]=w2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[1][0] = @3 */
  casadi_copy(w3, 25, res[1]);
  /* #11: @1 = 0.005 */
  w1 = 5.0000000000000001e-03;
  /* #12: @6 = quadf(@0, @2, @4) */
  arg1[0]=w0;
  arg1[1]=w2;
  arg1[2]=w4;
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #13: @1 = (@1*@6) */
  w1 *= w6;
  /* #14: output[2][0] = @1 */
  if (res[2]) res[2][0] = w1;
  return 0;
}

/* F_int:(x0[24],p0[151])->(xf[24],zf[25],qf) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3;
  const casadi_real **arg1=arg+2;
  casadi_real *w0=w+668, *w1=w+692, *w2=w+717, *w3=w+868, *w4=w+892, w5;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 24, w0);
  /* #1: @1 = zeros(25x1) */
  casadi_clear(w1, 25);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 151, w2);
  /* #3: {@3, @4, @5} = F(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=w2;
  res1[0]=w3;
  res1[1]=w4;
  res1[2]=(&w5);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][0] = @3 */
  casadi_copy(w3, 24, res[0]);
  /* #5: output[1][0] = @4 */
  casadi_copy(w4, 25, res[1]);
  /* #6: output[2][0] = @5 */
  if (res[2]) res[2][0] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_int(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_int_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_int_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_int_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_int_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_int_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_int_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_int_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_int_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_int_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real F_int_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_int_name_in(casadi_int i){
  switch (i) {
    case 0: return "x0";
    case 1: return "p0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_int_name_out(casadi_int i){
  switch (i) {
    case 0: return "xf";
    case 1: return "zf";
    case 2: return "qf";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_int_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_int_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_int_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 918;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
