/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) F_tgrids_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[84] = {80, 1, 0, 80, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79};
static const casadi_int casadi_s2[105] = {101, 1, 0, 101, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100};
static const casadi_int casadi_s3[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};

/* F_tgrids:(t0)->(tgrid[80],tgrid_x[101],tgrid_u[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=8.8587959512704210e-03;
  a2=(a0+a1);
  if (res[0]!=0) res[0][0]=a2;
  a2=4.0946686444073468e-02;
  a3=(a0+a2);
  if (res[0]!=0) res[0][1]=a3;
  a3=7.8765946176084706e-02;
  a4=(a0+a3);
  if (res[0]!=0) res[0][2]=a4;
  a4=1.0000000000000001e-01;
  a5=(a0+a4);
  if (res[0]!=0) res[0][3]=a5;
  a5=1.0885879595127042e-01;
  a6=(a0+a5);
  if (res[0]!=0) res[0][4]=a6;
  a6=1.4094668644407346e-01;
  a7=(a0+a6);
  if (res[0]!=0) res[0][5]=a7;
  a7=1.7876594617608471e-01;
  a8=(a0+a7);
  if (res[0]!=0) res[0][6]=a8;
  a8=2.0000000000000001e-01;
  a9=(a0+a8);
  if (res[0]!=0) res[0][7]=a9;
  a9=2.0885879595127044e-01;
  a10=(a0+a9);
  if (res[0]!=0) res[0][8]=a10;
  a10=2.4094668644407347e-01;
  a11=(a0+a10);
  if (res[0]!=0) res[0][9]=a11;
  a11=2.7876594617608469e-01;
  a12=(a0+a11);
  if (res[0]!=0) res[0][10]=a12;
  a12=2.9999999999999999e-01;
  a13=(a0+a12);
  if (res[0]!=0) res[0][11]=a13;
  a13=3.0885879595127042e-01;
  a14=(a0+a13);
  if (res[0]!=0) res[0][12]=a14;
  a14=3.4094668644407344e-01;
  a15=(a0+a14);
  if (res[0]!=0) res[0][13]=a15;
  a15=3.7876594617608472e-01;
  a16=(a0+a15);
  if (res[0]!=0) res[0][14]=a16;
  a16=4.0000000000000002e-01;
  a17=(a0+a16);
  if (res[0]!=0) res[0][15]=a17;
  a17=4.0885879595127045e-01;
  a18=(a0+a17);
  if (res[0]!=0) res[0][16]=a18;
  a18=4.4094668644407342e-01;
  a19=(a0+a18);
  if (res[0]!=0) res[0][17]=a19;
  a19=4.7876594617608470e-01;
  a20=(a0+a19);
  if (res[0]!=0) res[0][18]=a20;
  a20=5.0000000000000000e-01;
  a21=(a0+a20);
  if (res[0]!=0) res[0][19]=a21;
  a21=5.0885879595127048e-01;
  a22=(a0+a21);
  if (res[0]!=0) res[0][20]=a22;
  a22=5.4094668644407340e-01;
  a23=(a0+a22);
  if (res[0]!=0) res[0][21]=a23;
  a23=5.7876594617608468e-01;
  a24=(a0+a23);
  if (res[0]!=0) res[0][22]=a24;
  a24=5.9999999999999998e-01;
  a25=(a0+a24);
  if (res[0]!=0) res[0][23]=a25;
  a25=6.0885879595127046e-01;
  a26=(a0+a25);
  if (res[0]!=0) res[0][24]=a26;
  a26=6.4094668644407338e-01;
  a27=(a0+a26);
  if (res[0]!=0) res[0][25]=a27;
  a27=6.7876594617608466e-01;
  a28=(a0+a27);
  if (res[0]!=0) res[0][26]=a28;
  a28=6.9999999999999996e-01;
  a29=(a0+a28);
  if (res[0]!=0) res[0][27]=a29;
  a29=7.0885879595127044e-01;
  a30=(a0+a29);
  if (res[0]!=0) res[0][28]=a30;
  a30=7.4094668644407347e-01;
  a31=(a0+a30);
  if (res[0]!=0) res[0][29]=a31;
  a31=7.7876594617608474e-01;
  a32=(a0+a31);
  if (res[0]!=0) res[0][30]=a32;
  a32=8.0000000000000004e-01;
  a33=(a0+a32);
  if (res[0]!=0) res[0][31]=a33;
  a33=8.0885879595127042e-01;
  a34=(a0+a33);
  if (res[0]!=0) res[0][32]=a34;
  a34=8.4094668644407344e-01;
  a35=(a0+a34);
  if (res[0]!=0) res[0][33]=a35;
  a35=8.7876594617608461e-01;
  a36=(a0+a35);
  if (res[0]!=0) res[0][34]=a36;
  a36=9.0000000000000002e-01;
  a37=(a0+a36);
  if (res[0]!=0) res[0][35]=a37;
  a37=9.0885879595127039e-01;
  a38=(a0+a37);
  if (res[0]!=0) res[0][36]=a38;
  a38=9.4094668644407342e-01;
  a39=(a0+a38);
  if (res[0]!=0) res[0][37]=a39;
  a39=9.7876594617608459e-01;
  a40=(a0+a39);
  if (res[0]!=0) res[0][38]=a40;
  a40=1.;
  a41=(a0+a40);
  if (res[0]!=0) res[0][39]=a41;
  a41=1.0088587959512705e+00;
  a42=(a0+a41);
  if (res[0]!=0) res[0][40]=a42;
  a42=1.0409466864440735e+00;
  a43=(a0+a42);
  if (res[0]!=0) res[0][41]=a43;
  a43=1.0787659461760846e+00;
  a44=(a0+a43);
  if (res[0]!=0) res[0][42]=a44;
  a44=1.1000000000000001e+00;
  a45=(a0+a44);
  if (res[0]!=0) res[0][43]=a45;
  a45=1.1088587959512703e+00;
  a46=(a0+a45);
  if (res[0]!=0) res[0][44]=a46;
  a46=1.1409466864440734e+00;
  a47=(a0+a46);
  if (res[0]!=0) res[0][45]=a47;
  a47=1.1787659461760847e+00;
  a48=(a0+a47);
  if (res[0]!=0) res[0][46]=a48;
  a48=1.2000000000000000e+00;
  a49=(a0+a48);
  if (res[0]!=0) res[0][47]=a49;
  a49=1.2088587959512704e+00;
  a50=(a0+a49);
  if (res[0]!=0) res[0][48]=a50;
  a50=1.2409466864440735e+00;
  a51=(a0+a50);
  if (res[0]!=0) res[0][49]=a51;
  a51=1.2787659461760845e+00;
  a52=(a0+a51);
  if (res[0]!=0) res[0][50]=a52;
  a52=1.3000000000000000e+00;
  a53=(a0+a52);
  if (res[0]!=0) res[0][51]=a53;
  a53=1.3088587959512705e+00;
  a54=(a0+a53);
  if (res[0]!=0) res[0][52]=a54;
  a54=1.3409466864440733e+00;
  a55=(a0+a54);
  if (res[0]!=0) res[0][53]=a55;
  a55=1.3787659461760846e+00;
  a56=(a0+a55);
  if (res[0]!=0) res[0][54]=a56;
  a56=1.3999999999999999e+00;
  a57=(a0+a56);
  if (res[0]!=0) res[0][55]=a57;
  a57=1.4088587959512704e+00;
  a58=(a0+a57);
  if (res[0]!=0) res[0][56]=a58;
  a58=1.4409466864440734e+00;
  a59=(a0+a58);
  if (res[0]!=0) res[0][57]=a59;
  a59=1.4787659461760847e+00;
  a60=(a0+a59);
  if (res[0]!=0) res[0][58]=a60;
  a60=1.5000000000000000e+00;
  a61=(a0+a60);
  if (res[0]!=0) res[0][59]=a61;
  a61=1.5088587959512705e+00;
  a62=(a0+a61);
  if (res[0]!=0) res[0][60]=a62;
  a62=1.5409466864440735e+00;
  a63=(a0+a62);
  if (res[0]!=0) res[0][61]=a63;
  a63=1.5787659461760846e+00;
  a64=(a0+a63);
  if (res[0]!=0) res[0][62]=a64;
  a64=1.6000000000000001e+00;
  a65=(a0+a64);
  if (res[0]!=0) res[0][63]=a65;
  a65=1.6088587959512703e+00;
  a66=(a0+a65);
  if (res[0]!=0) res[0][64]=a66;
  a66=1.6409466864440734e+00;
  a67=(a0+a66);
  if (res[0]!=0) res[0][65]=a67;
  a67=1.6787659461760847e+00;
  a68=(a0+a67);
  if (res[0]!=0) res[0][66]=a68;
  a68=1.7000000000000000e+00;
  a69=(a0+a68);
  if (res[0]!=0) res[0][67]=a69;
  a69=1.7088587959512704e+00;
  a70=(a0+a69);
  if (res[0]!=0) res[0][68]=a70;
  a70=1.7409466864440735e+00;
  a71=(a0+a70);
  if (res[0]!=0) res[0][69]=a71;
  a71=1.7787659461760845e+00;
  a72=(a0+a71);
  if (res[0]!=0) res[0][70]=a72;
  a72=1.8000000000000000e+00;
  a73=(a0+a72);
  if (res[0]!=0) res[0][71]=a73;
  a73=1.8088587959512705e+00;
  a74=(a0+a73);
  if (res[0]!=0) res[0][72]=a74;
  a74=1.8409466864440733e+00;
  a75=(a0+a74);
  if (res[0]!=0) res[0][73]=a75;
  a75=1.8787659461760846e+00;
  a76=(a0+a75);
  if (res[0]!=0) res[0][74]=a76;
  a76=1.8999999999999999e+00;
  a77=(a0+a76);
  if (res[0]!=0) res[0][75]=a77;
  a77=1.9088587959512704e+00;
  a78=(a0+a77);
  if (res[0]!=0) res[0][76]=a78;
  a78=1.9409466864440734e+00;
  a79=(a0+a78);
  if (res[0]!=0) res[0][77]=a79;
  a79=1.9787659461760847e+00;
  a80=(a0+a79);
  if (res[0]!=0) res[0][78]=a80;
  a80=2.;
  a81=(a0+a80);
  if (res[0]!=0) res[0][79]=a81;
  if (res[1]!=0) res[1][0]=a0;
  a1=(a0+a1);
  if (res[1]!=0) res[1][1]=a1;
  a2=(a0+a2);
  if (res[1]!=0) res[1][2]=a2;
  a3=(a0+a3);
  if (res[1]!=0) res[1][3]=a3;
  a3=(a0+a4);
  if (res[1]!=0) res[1][4]=a3;
  a3=(a0+a4);
  if (res[1]!=0) res[1][5]=a3;
  a5=(a0+a5);
  if (res[1]!=0) res[1][6]=a5;
  a6=(a0+a6);
  if (res[1]!=0) res[1][7]=a6;
  a7=(a0+a7);
  if (res[1]!=0) res[1][8]=a7;
  a7=(a0+a8);
  if (res[1]!=0) res[1][9]=a7;
  a7=(a0+a8);
  if (res[1]!=0) res[1][10]=a7;
  a9=(a0+a9);
  if (res[1]!=0) res[1][11]=a9;
  a10=(a0+a10);
  if (res[1]!=0) res[1][12]=a10;
  a11=(a0+a11);
  if (res[1]!=0) res[1][13]=a11;
  a11=(a0+a12);
  if (res[1]!=0) res[1][14]=a11;
  a11=(a0+a12);
  if (res[1]!=0) res[1][15]=a11;
  a13=(a0+a13);
  if (res[1]!=0) res[1][16]=a13;
  a14=(a0+a14);
  if (res[1]!=0) res[1][17]=a14;
  a15=(a0+a15);
  if (res[1]!=0) res[1][18]=a15;
  a15=(a0+a16);
  if (res[1]!=0) res[1][19]=a15;
  a15=(a0+a16);
  if (res[1]!=0) res[1][20]=a15;
  a17=(a0+a17);
  if (res[1]!=0) res[1][21]=a17;
  a18=(a0+a18);
  if (res[1]!=0) res[1][22]=a18;
  a19=(a0+a19);
  if (res[1]!=0) res[1][23]=a19;
  a19=(a0+a20);
  if (res[1]!=0) res[1][24]=a19;
  a19=(a0+a20);
  if (res[1]!=0) res[1][25]=a19;
  a21=(a0+a21);
  if (res[1]!=0) res[1][26]=a21;
  a22=(a0+a22);
  if (res[1]!=0) res[1][27]=a22;
  a23=(a0+a23);
  if (res[1]!=0) res[1][28]=a23;
  a23=(a0+a24);
  if (res[1]!=0) res[1][29]=a23;
  a23=(a0+a24);
  if (res[1]!=0) res[1][30]=a23;
  a25=(a0+a25);
  if (res[1]!=0) res[1][31]=a25;
  a26=(a0+a26);
  if (res[1]!=0) res[1][32]=a26;
  a27=(a0+a27);
  if (res[1]!=0) res[1][33]=a27;
  a27=(a0+a28);
  if (res[1]!=0) res[1][34]=a27;
  a27=(a0+a28);
  if (res[1]!=0) res[1][35]=a27;
  a29=(a0+a29);
  if (res[1]!=0) res[1][36]=a29;
  a30=(a0+a30);
  if (res[1]!=0) res[1][37]=a30;
  a31=(a0+a31);
  if (res[1]!=0) res[1][38]=a31;
  a31=(a0+a32);
  if (res[1]!=0) res[1][39]=a31;
  a31=(a0+a32);
  if (res[1]!=0) res[1][40]=a31;
  a33=(a0+a33);
  if (res[1]!=0) res[1][41]=a33;
  a34=(a0+a34);
  if (res[1]!=0) res[1][42]=a34;
  a35=(a0+a35);
  if (res[1]!=0) res[1][43]=a35;
  a35=(a0+a36);
  if (res[1]!=0) res[1][44]=a35;
  a35=(a0+a36);
  if (res[1]!=0) res[1][45]=a35;
  a37=(a0+a37);
  if (res[1]!=0) res[1][46]=a37;
  a38=(a0+a38);
  if (res[1]!=0) res[1][47]=a38;
  a39=(a0+a39);
  if (res[1]!=0) res[1][48]=a39;
  a39=(a0+a40);
  if (res[1]!=0) res[1][49]=a39;
  a39=(a0+a40);
  if (res[1]!=0) res[1][50]=a39;
  a41=(a0+a41);
  if (res[1]!=0) res[1][51]=a41;
  a42=(a0+a42);
  if (res[1]!=0) res[1][52]=a42;
  a43=(a0+a43);
  if (res[1]!=0) res[1][53]=a43;
  a43=(a0+a44);
  if (res[1]!=0) res[1][54]=a43;
  a43=(a0+a44);
  if (res[1]!=0) res[1][55]=a43;
  a45=(a0+a45);
  if (res[1]!=0) res[1][56]=a45;
  a46=(a0+a46);
  if (res[1]!=0) res[1][57]=a46;
  a47=(a0+a47);
  if (res[1]!=0) res[1][58]=a47;
  a47=(a0+a48);
  if (res[1]!=0) res[1][59]=a47;
  a47=(a0+a48);
  if (res[1]!=0) res[1][60]=a47;
  a49=(a0+a49);
  if (res[1]!=0) res[1][61]=a49;
  a50=(a0+a50);
  if (res[1]!=0) res[1][62]=a50;
  a51=(a0+a51);
  if (res[1]!=0) res[1][63]=a51;
  a51=(a0+a52);
  if (res[1]!=0) res[1][64]=a51;
  a51=(a0+a52);
  if (res[1]!=0) res[1][65]=a51;
  a53=(a0+a53);
  if (res[1]!=0) res[1][66]=a53;
  a54=(a0+a54);
  if (res[1]!=0) res[1][67]=a54;
  a55=(a0+a55);
  if (res[1]!=0) res[1][68]=a55;
  a55=(a0+a56);
  if (res[1]!=0) res[1][69]=a55;
  a55=(a0+a56);
  if (res[1]!=0) res[1][70]=a55;
  a57=(a0+a57);
  if (res[1]!=0) res[1][71]=a57;
  a58=(a0+a58);
  if (res[1]!=0) res[1][72]=a58;
  a59=(a0+a59);
  if (res[1]!=0) res[1][73]=a59;
  a59=(a0+a60);
  if (res[1]!=0) res[1][74]=a59;
  a59=(a0+a60);
  if (res[1]!=0) res[1][75]=a59;
  a61=(a0+a61);
  if (res[1]!=0) res[1][76]=a61;
  a62=(a0+a62);
  if (res[1]!=0) res[1][77]=a62;
  a63=(a0+a63);
  if (res[1]!=0) res[1][78]=a63;
  a63=(a0+a64);
  if (res[1]!=0) res[1][79]=a63;
  a63=(a0+a64);
  if (res[1]!=0) res[1][80]=a63;
  a65=(a0+a65);
  if (res[1]!=0) res[1][81]=a65;
  a66=(a0+a66);
  if (res[1]!=0) res[1][82]=a66;
  a67=(a0+a67);
  if (res[1]!=0) res[1][83]=a67;
  a67=(a0+a68);
  if (res[1]!=0) res[1][84]=a67;
  a67=(a0+a68);
  if (res[1]!=0) res[1][85]=a67;
  a69=(a0+a69);
  if (res[1]!=0) res[1][86]=a69;
  a70=(a0+a70);
  if (res[1]!=0) res[1][87]=a70;
  a71=(a0+a71);
  if (res[1]!=0) res[1][88]=a71;
  a71=(a0+a72);
  if (res[1]!=0) res[1][89]=a71;
  a71=(a0+a72);
  if (res[1]!=0) res[1][90]=a71;
  a73=(a0+a73);
  if (res[1]!=0) res[1][91]=a73;
  a74=(a0+a74);
  if (res[1]!=0) res[1][92]=a74;
  a75=(a0+a75);
  if (res[1]!=0) res[1][93]=a75;
  a75=(a0+a76);
  if (res[1]!=0) res[1][94]=a75;
  a75=(a0+a76);
  if (res[1]!=0) res[1][95]=a75;
  a77=(a0+a77);
  if (res[1]!=0) res[1][96]=a77;
  a78=(a0+a78);
  if (res[1]!=0) res[1][97]=a78;
  a79=(a0+a79);
  if (res[1]!=0) res[1][98]=a79;
  a79=(a0+a80);
  if (res[1]!=0) res[1][99]=a79;
  a80=(a0+a80);
  if (res[1]!=0) res[1][100]=a80;
  if (res[2]!=0) res[2][0]=a0;
  a4=(a0+a4);
  if (res[2]!=0) res[2][1]=a4;
  a8=(a0+a8);
  if (res[2]!=0) res[2][2]=a8;
  a12=(a0+a12);
  if (res[2]!=0) res[2][3]=a12;
  a16=(a0+a16);
  if (res[2]!=0) res[2][4]=a16;
  a20=(a0+a20);
  if (res[2]!=0) res[2][5]=a20;
  a24=(a0+a24);
  if (res[2]!=0) res[2][6]=a24;
  a28=(a0+a28);
  if (res[2]!=0) res[2][7]=a28;
  a32=(a0+a32);
  if (res[2]!=0) res[2][8]=a32;
  a36=(a0+a36);
  if (res[2]!=0) res[2][9]=a36;
  a40=(a0+a40);
  if (res[2]!=0) res[2][10]=a40;
  a44=(a0+a44);
  if (res[2]!=0) res[2][11]=a44;
  a48=(a0+a48);
  if (res[2]!=0) res[2][12]=a48;
  a52=(a0+a52);
  if (res[2]!=0) res[2][13]=a52;
  a56=(a0+a56);
  if (res[2]!=0) res[2][14]=a56;
  a60=(a0+a60);
  if (res[2]!=0) res[2][15]=a60;
  a64=(a0+a64);
  if (res[2]!=0) res[2][16]=a64;
  a68=(a0+a68);
  if (res[2]!=0) res[2][17]=a68;
  a72=(a0+a72);
  if (res[2]!=0) res[2][18]=a72;
  a0=(a0+a76);
  if (res[2]!=0) res[2][19]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_tgrids(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_tgrids_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_tgrids_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_tgrids_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_tgrids_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_tgrids_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_tgrids_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_tgrids_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_tgrids_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int F_tgrids_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real F_tgrids_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_tgrids_name_in(casadi_int i){
  switch (i) {
    case 0: return "t0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_tgrids_name_out(casadi_int i){
  switch (i) {
    case 0: return "tgrid";
    case 1: return "tgrid_x";
    case 2: return "tgrid_u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_tgrids_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_tgrids_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_tgrids_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
